### ISSUE TITLE
correct mode to run

### ISSUE THREAD

**Issue by empereira** [tiian/flom#21]
hello,

I have 3 python scripts:

- script1.py
- script2.py
- script3.py

They need to execute forever and in the order above and each in their time period. Possibly with --lock-mode=EX 

I'm trying via the bash script.

```
#!/bin/bash

flom -d -1 -l EX -- python script1.py & 
flom -d -1 -l EX -- python script2.py &
flom -d -1 -l EX -- python script3.py &
wait
```

Executing this way, returns the error:

`(flom:28781): WARNING **: Unable to execute command '-l'`

**Comment by tiian** [comment]
Hi, the use case is not clear to me "execute forever and in the order above and each in their time period"... I don't get the point.

If script1.py executes forever and it gets the lock, script2.py will never execute and the same applies to script3.py. Here is a description of [resources and lock modes](https://www.tiian.org/flom/Resource.html)

If you need to execute the 3 scripts in the exact order, this [use case](https://www.tiian.org/flom/FLoM_by_examples/Use_Case_16.html) provides an example with 2 jobs; you need to execute 3 consecutive jobs and you can extend it using 2 [simple resources](https://www.tiian.org/flom/Resource.html).

Coming back to your example there are several flaws:

1. "-d" is required to start a stand-alone flom daemon and should not be necessary in your use case; typical usage is in a [distributed environment](https://www.tiian.org/flom/Distributed_Features.html); pay attention a stand-alone flom daemon requires management and monitoring
2. "-l EX" is the default behaviour, you can skip it; anyway an exclusive lock means that a single command/script will be executed by one of the flom instances you activate and this seems to be in contradiction with your explanation
3. and most important:

flom -- command1 &
flom -- command2 &
flom -- command3 &

guarantees only the order of start of the 3 flom commands, but can **not** guarantee the order of execution because for some reasons it may happen Linux kernel steal the CPU from flom -- command1 before it got the lock and execute flom -- command 2.
That's a typical race condition and could be difficult to debug.
At minimum you should use something like;

flom -- command1 &
sleep 1
flom -- command2 &
sleep 1
flom -- command3 &

but there's no guarantee you will get the desired order if the system load is under big pressure.
To obtain a specific execution order, the correct implementation using flom is described in this [example](https://www.tiian.org/flom/FLoM_by_examples/FLoM_by_examples.html) and in this [example](https://www.tiian.org/flom/FLoM_by_examples/Use_Case_17.html).

As a final note, something is not properly configured in your system: I tried an example as the one you reported:

    tiian@ubuntu1004:/tmp$ cat script.sh 
    #!/bin/bash
    
    flom -d -1 -l EX -- sleep 5 &
    flom -d -1 -l EX -- sleep 5 &
    flom -d -1 -l EX -- sleep 5 &
    wait

and it generates no error:

    tiian@ubuntu1004:/tmp$ ./script.sh 
    tiian@ubuntu1004:/tmp$ 

It's suggested to read the full documentation available [here](https://www.tiian.org/flom/) before going on.

**Comment by empereira** [comment]
Nice explanation!!! Thanks, @tiian !!!

When I said "forever" I meant, let it run like a daemon in the system. Let it run the 3 scripts until I kill the process.

Now, I run with a while loop and seems to work.

```
while true; do
   flom -- command1 &
   sleep 1
   flom -- command2 &
   sleep 1
   flom -- command3 &
done
```

I need it that way because the first script adds information that the other 2 need. The second one has fast execution. It takes about 3 minutes, but the third takes about 20 minutes.

I'm analyzing the execution via the command below:
`watch -n1 'ps aux |grep python |grep -v grep'`

Would a better way to analyze the execution of the script?
