### ISSUE TITLE
Distribution releases? 

### ISSUE THREAD

**Issue by aadrian** [tiian/flom#22]
Hi,

Any chance creating distribution specific releases? e.g. "deb" for Debian/Ubuntu and "rpm" for the others?

On many production systems: build tooling and doing "make install" is not allowed.

Thank you.

**Comment by tiian** [comment]
Hi,
first of all, thanks for your request and your interest in the flom project.
I'm not against standard packaging and I know it provides a lot of value for system engineers when operations is concerned.
On my side I have never started to provide binary packages for some reasons:

- I have never done it (no skill)
- As a consequence of the previous point, I have no idea about how many build pipelines must be created for producing and testing the binary packages, but I fear it's a huge task, especially if a "deb" must be run on "any sort of Debian derivative" and an "rpm" must run on "any sort of rpm based distribution"
- I don't think, in the short term, to be able to produce some decent support for "deb" and "rpm" due to lack of time
- last but not least, this could be a topic where the "community" steps in: someone with skill and experience might join the project to produce and maintain binary packages.

In the meantime, as a workaround, you could build flom on dev/test systems and installing it copying the binaries in production systems: in the end, it's an easy software with few files that must be copied (look at the copy made by "make install" step).

Anyway, I leave this issue open as an "enhancement", hoping someone will help or before or later I'll be able to provide something in this direction.

By the way, please reply with the Linux distributions you are using, just to figure out what packages would help you.

**Comment by aadrian** [comment]
> In the meantime, as a workaround, you could build flom on dev/test systems and installing it copying the binaries in production systems

Is it a statically linked binary without dependencies ? (like many of the Golang projects do ? ) so that deployment is just copy of single binary somewhere? If yes, than no distribution package is really needed, just publish with a GitHub Actions pipeline the binary to each release automatically (there are many examples for that).


> By the way, please reply with the Linux distributions you are using

I have most servers with Debian 10 and RHEL 7 and 8.

**Comment by tiian** [comment]
It's not a statically linked binary, flom carries it's own shared library and links many others as below (example from a very old Ubuntu 10.04):

    tiian@ubuntu1004:~/flom$ ldd /usr/local/bin/flom 
    	linux-vdso.so.1 =>  (0x00007fff2f0f7000)
    	libgthread-2.0.so.0 => /usr/lib/libgthread-2.0.so.0 (0x00007f7b651c4000)
    	libglib-2.0.so.0 => /lib/libglib-2.0.so.0 (0x00007f7b64ee6000)
    	libpthread.so.0 => /lib/libpthread.so.0 (0x00007f7b64cc8000)
    	librt.so.1 => /lib/librt.so.1 (0x00007f7b64ac0000)
    	libcrypto.so.0.9.8 => /lib/libcrypto.so.0.9.8 (0x00007f7b6472f000)
    	libflom.so.0 => /usr/local/lib/libflom.so.0 (0x00007f7b644f0000)
    	libssl.so.0.9.8 => /lib/libssl.so.0.9.8 (0x00007f7b6429c000)
    	libdbus-1.so.3 => /lib/libdbus-1.so.3 (0x00007f7b6405d000)
    	libc.so.6 => /lib/libc.so.6 (0x00007f7b63cd3000)
    	libpcre.so.3 => /lib/libpcre.so.3 (0x00007f7b63aa5000)
    	/lib64/ld-linux-x86-64.so.2 (0x00007f7b653d1000)
    	libdl.so.2 => /lib/libdl.so.2 (0x00007f7b638a1000)
    	libz.so.1 => /lib/libz.so.1 (0x00007f7b63689000)

but this page describes something that can be of some help for you: 
https://wiki.debian.org/CheckInstall
I have never tried it, but it sounds interesting.

**Comment by tiian** [comment]
No further feedback from the user.

**Comment by andreasstieger** [comment]
rpm for openSUSE in https://build.opensuse.org/request/show/1083763

**Comment by tiian** [comment]
> rpm for openSUSE in https://build.opensuse.org/request/show/1083763

Page https://www.tiian.org/flom/ contains now a reference to the openSUSE package.
